apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: prepare-image-artifacts
spec:
  description: >-
    This task can be used to download required artifacts for building
    casual image or copy built artifacts to the image build location.

  workspaces:
    - name: source
      description: The workspace consisting of the gradle project.
  params:
    - name: IMAGE
      description: Gradle base image.
      type: string
      default: docker.io/library/gradle:jdk17@sha256:27ed98487dd9c155d555955084dfd33f32d9f7ac5a90a79b1323ab002a1a8b6e
    - name: casual-java-integration-test-src
      type: string
      default: "$(workspaces.source.path)/casual-java-integration-test"
    - name: casual-java-src
      type: string
      default: "$(workspaces.source.path)/casual-java"
    - name: casual-caller-src
      type: string
      default: "$(workspaces.source.path)/casual-caller"
    - name: casual-java-test-apps-src
      type: string
      default: "$(workspaces.source.path)/casual-java-test-apps/casual-java-test-app"
    - name: built-casual-java
      description: Boolean specifying if casual-java has been built from source.
      type: string
    - name: built-casual-caller
      description: Boolean specifying if casual-caller has been built from source.
      type: string
    - name: built-casual-java-test-apps
      description: Boolean specifying if casual-java-test-apps has been built from source.
      type: string
    - name: artifact-destination
      description: Destination for downloaded or built artifacts.
      type: string
      default: "$(workspaces.source.path)/casual-java-integration-test/images/casual-java/docker/files"
  results:
    - name: casual-java-version
      description: Version of casual java artifacts.
    - name: casual-caller-version
      description: Version of casual caller artifacts.
    - name: casual-test-app-version
      description: Version of casual test app artifacts.
  steps:
    - name: check-version
      image: $(params.IMAGE)
      env:
        - name: CASUAL_JAVA_SRC
          value: "$(params.casual-java-src)"
        - name: CASUAL_CALLER_SRC
          value: "$(params.casual-caller-src)"
        - name: CASUAL_TEST_APPS_SRC
          value: "$(params.casual-java-test-apps-src)"
      workingDir: "$(params.casual-java-integration-test-src)"
      script: |
        #!/usr/bin/bash
        set -e
        
        casual_java_version=$(grep ^version $CASUAL_JAVA_SRC/versions.gradle | cut -d '=' -f2 | tr -d \ \'\")
        echo -n $casual_java_version | tee $(results.casual-java-version.path)
        casual_caller_version=$(grep ^version $CASUAL_CALLER_SRC/versions.gradle | cut -d '=' -f2 | tr -d \ \'\")
        echo -n $casual_caller_version | tee $(results.casual-caller-version.path)
        casual_test_app_version=$(grep ^version $CASUAL_TEST_APPS_SRC/versions.gradle | cut -d '=' -f2 | tr -d \ \'\")
        echo -n $casual_test_app_version | tee $(results.casual-test-app-version.path)
    - name: download-artifacts-casual-java
      image: $(params.IMAGE)
      env:
        - name: CASUAL_JAVA_INTEGRATION_TEST_SRC
          value: "$(params.casual-java-integration-test-src)"
        - name: DESTINATION
          value: "$(params.artifact-destination)"
      workingDir: "$(params.casual-java-integration-test-src)"
      script: |
        #!/usr/bin/bash
        set -e        
        export CASUAL_JAVA_VERSION=$(cat $(results.casual-java-version.path))
        echo "CASUAL_JAVA_VERSION: " $CASUAL_JAVA_VERSION
        cmd="./gradlew downloadCasualJava"
        echo "Running gradle task with command below"
        echo "$cmd"
        eval "$cmd"
        echo "Copying downloaded artifacts"
        cp $CASUAL_JAVA_INTEGRATION_TEST_SRC/build/runtime/* $DESTINATION        
        ls -l $DESTINATION
        cd $DESTINATION
        pwd
      when:
      - input: "$(params.built-casual-java)"
        operator: in
        values: [ "false" ]
    - name: copy-built-artifacts-casual-java
      image: $(params.IMAGE)
      env:
        - name: CASUAL_JAVA_SRC
          value: "$(params.casual-java-src)"
        - name: DESTINATION
          value: "$(params.artifact-destination)"
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/bash
        set -e
        echo "Copying built artifacts"
        cp $CASUAL_JAVA_SRC/dist/* $DESTINATION
        ls -l $DESTINATION
        cd $DESTINATION
        pwd
      when:
      - input: "$(params.built-casual-java)"
        operator: in
        values: [ "true" ]
    - name: download-artifacts-casual-caller
      image: $(params.IMAGE)
      env:
        - name: CASUAL_JAVA_INTEGRATION_TEST_SRC
          value: "$(params.casual-java-integration-test-src)"
        - name: DESTINATION
          value: "$(params.artifact-destination)"
      workingDir: "$(params.casual-java-integration-test-src)"
      script: |
        #!/usr/bin/bash
        set -e
        export CASUAL_CALLER_VERSION=$(cat $(results.casual-caller-version.path))
        echo "CASUAL_CALLER_VERSION: " $CASUAL_CALLER_VERSION
        cmd="./gradlew downloadCasualCaller"
        echo "Running gradle task with command below"
        echo "$cmd"
        eval "$cmd"
        echo "Copying downloaded artifacts"
        cp $CASUAL_JAVA_INTEGRATION_TEST_SRC/build/runtime/* $DESTINATION
        ls -l $DESTINATION
        cd $DESTINATION
        pwd
      when:
        - input: "$(params.built-casual-caller)"
          operator: in
          values: [ "false" ]
    - name: copy-built-artifacts-casual-caller
      image: $(params.IMAGE)
      env:
        - name: CASUAL_CALLER_SRC
          value: "$(params.casual-caller-src)"
        - name: DESTINATION
          value: "$(params.artifact-destination)"
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/bash
        set -e
        echo "Copying built artifacts"
        cp $CASUAL_CALLER_SRC/dist/* $DESTINATION
        ls -l $DESTINATION
        cd $DESTINATION
        pwd
      when:
        - input: "$(params.built-casual-caller)"
          operator: in
          values: [ "true" ]
    - name: copy-casual-java-test-resources
      image: $(params.IMAGE)
      env:
        - name: CASUAL_JAVA_SRC
          value: "$(params.casual-java-src)"
        - name: DESTINATION
          value: "$(params.artifact-destination)/configs"
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/bash
        set -e
        echo "Copying built artifacts"
        mkdir -p $DESTINATION
        cp -r $CASUAL_JAVA_SRC/casual/casual-api/src/test/resources/* $DESTINATION
        ls -l $DESTINATION
        cd $DESTINATION
        pwd
    - name: copy-built-artifacts-casual-java-test-apps
      image: $(params.IMAGE)
      env:
        - name: CASUAL_JAVA_TEST_APPS_SRC
          value: "$(params.casual-java-test-apps-src)"
        - name: DESTINATION
          value: "$(params.artifact-destination)"
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/bash
        set -e
        echo "Copying built artifacts"
        cp $CASUAL_JAVA_TEST_APPS_SRC/dist/* $DESTINATION
        ls -l $DESTINATION
        cd $DESTINATION
        pwd
      when:
        - input: "$(params.built-casual-java-test-apps)"
          operator: in
          values: [ "true" ]
