apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-casual-java-repo-pipeline-run-
spec:
  workspaces:
    - name: pipeline-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
    - name: image-registry
      value: 192.168.68.106:32000
    - name: repository-casual-java-integration-test
      value:
        revision: "feature/tekton-build"
    - name: repository-casual-java
      value:
        revision: "3.4.0"
        build: "false"
    - name: repository-casual-caller
      value:
        revision: "dev"
        build: "false"
    - name: repository-casual-java-test-apps
      value:
        revision: "dev"
        build: "true"
    - name: casual-java-image
      value:
        name: "casual-java"
        version: "3.4.0-SNAPSHOT"
  pipelineRef:
    name: build-casual-java-repo-pipeline