apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-casual-java-repo-pipeline-run-
spec:
  workspaces:
    - name: pipeline-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
    - name: repository
      value:
        url: https://github.com/casualcore/casual-java-integration-test.git
        revision: "feature/tekton-build"
    - name: repository-casual-java
      value:
        url: https://github.com/casualcore/casual-java.git
        revision: "feature/3.2/initialise-fieled-on-startup"
  pipelineRef:
    name: build-casual-java-repo-pipeline