apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-casual-java-repo-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repository
      description: "Repository to build."
      type: object
      properties:
        url:
          type: string
        revision:
          type: string
    - name: repository-casual-java
      description: "Repository to build casual-java."
      type: object
      properties:
        url:
          type: string
        revision:
          type: string
    - name: image-registry
      description: "Image registry url."
      type: string
    - name: casual-java-image
      description: "Image details for created casual-java image."
      type: object
      properties:
        name:
          type: string
        version:
          type: string
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repository.url)
        - name: revision
          value: $(params.repository.revision)
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: clone-casual-java
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repository-casual-java.url)
        - name: revision
          value: $(params.repository-casual-java.revision)
        - name: subdirectory
          value: "casual-java"
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: build
      runAfter:
        - clone
        - clone-casual-java
      taskRef:
        name: gradle
      params:
        - name: PROJECT_DIR
          value: "./casual-java"
        - name: GRADLE_COMMAND
          value: "./gradlew"
        - name: TASKS
          value:
            - assemble
            - dist
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: integration-test
      runAfter:
        - build
      taskRef:
        name: gradle
      params:
        - name: PROJECT_DIR
          value: "./casual-java"
        - name: GRADLE_COMMAND
          value: "./gradlew"
        - name: TASKS
          value:
            - intTest
      workspaces:
        - name: source
          workspace: pipeline-workspace
#    - name: build-image
#      runAfter:
#        - build
#      taskRef:
#        name: buildah
#      params:
#        - name: DOCKERFILE
#          value: ./images/casual-java/docker/Dockerfile
#        - name: IMAGE
#          value: $(params.image-registry)/$(params.casual-java-image.name):$(params.casual-java-image.version)
#        - name: BUILD_ARGS
#          value:
#            - "CASUAL_VERSION=3.3.1"
#        - name: TLSVERIFY
#          value: 'false'
#      workspaces:
#        - name: source
#          workspace: pipeline-workspace