apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-casual-java-repo-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repository-casual-java-integration-test
      description: "Repository for casual-java-integration-test."
      type: object
      properties:
        url:
          type: string
        revision:
          type: string
        default:
          url: https://github.com/casualcore/casual-java-integration-test.git
    - name: repository-casual-java
      description: "Repository for casual-java."
      type: object
      properties:
        url:
          type: string
        revision:
          type: string
        default:
          url: https://github.com/casualcore/casual-java.git
    - name: repository-casual-java-test-app
      description: "Repository for casual-java-test-app."
      type: object
      properties:
        url:
          type: string
        revision:
          type: string
        default:
          url: https://github.com/casualcore/casual-java-test-app.git
    - name: image-registry
      description: "Image registry url."
      type: string
    - name: casual-java-image
      description: "Image details for created casual-java image."
      type: object
      properties:
        name:
          type: string
        version:
          type: string
  tasks:
    - name: clone-casual-java-integration-test
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repository-casual-java-integration-test.url)
        - name: revision
          value: $(params.repository-casual-java-integration-test.revision)
        - name: subdirectory
          value: "casual-java-integration-test"
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: clone-casual-java
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repository-casual-java.url)
        - name: revision
          value: $(params.repository-casual-java.revision)
        - name: subdirectory
          value: "casual-java"
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: clone-casual-java-test-app
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repository-casual-java-test-app.url)
        - name: revision
          value: $(params.repository-casual-java-test-app.revision)
        - name: subdirectory
          value: "casual-java-test-app"
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: build-casual-java
      runAfter:
        - clone-casual-java
      taskRef:
        name: gradle
      params:
        - name: PROJECT_DIR
          value: "./casual-java"
        - name: GRADLE_COMMAND
          value: "./gradlew"
        - name: TASKS
          value:
            - assemble
            - dist
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: build-casual-java-test-app
      runAfter:
        - clone-casual-java-test-app
      taskRef:
        name: gradle
      params:
        - name: PROJECT_DIR
          value: "./casual-java-test-app"
        - name: GRADLE_COMMAND
          value: "./gradlew"
        - name: TASKS
          value:
            - assemble
            - dist
      workspaces:
        - name: source
          workspace: pipeline-workspace
#    - name: integration-test
#      runAfter:
#        - build
#      taskRef:
#        name: gradle
#      params:
#        - name: PROJECT_DIR
#          value: "./casual-java"
#        - name: GRADLE_COMMAND
#          value: "./gradlew"
#        - name: TASKS
#          value:
#            - intTest
#      workspaces:
#        - name: source
#          workspace: pipeline-workspace
    - name: build-image
      runAfter:
        - clone-casual-java-integration-test
        - build-casual-java
        - build-casual-java-test-app
      taskRef:
        name: buildah
      params:
        - name: DOCKERFILE
          value: ./casual-java-integration-test/images/casual-java/docker/Dockerfile
        - name: IMAGE
          value: $(params.image-registry)/$(params.casual-java-image.name):$(params.casual-java-image.version)
        - name: BUILD_ARGS
          value:
            - "CASUAL_VERSION=$(params.casual-java-image.version)"
        - name: TLSVERIFY
          value: 'false'
      workspaces:
        - name: source
          workspace: pipeline-workspace