domain:
  default:
    server:
      instances: 1
      restart: false
  gateway:
    inbound:
      groups:
        - alias: "casual-inbound"
          connections:
            - address: 0.0.0.0:7771
              discovery:
                forward: true
              note: "discovery will be forward to all outbounds"
    outbound:
      groups:
        - alias: "java"
          connections:
            - address: casual-java-service:7772
  queue:
    note: "Example queue setup."
    default:
      queue:
        retry:
          count: 3
          delay: "20s"
      directory: "${CASUAL_DOMAIN_HOME}/queue/groups"
    groups:
      - alias: "EXAMPLE"
        queues:
          - name: "ex1"
          - name: "ex2"
  name: test-domain
  servers:
    - instances: 1
      note: exampleserver
      path: ${CASUAL_HOME}/example/bin/casual-example-server