domain:
  default:
    server:
      instances: 1
      restart: false
  gateway:
    inbound:
      groups:
        - alias: "casual-inbound"
          connections:
            - address: 0.0.0.0:7771
  queue:
    note: "Example queue setup."
    default:
      queue:
        retry: 0
        delay: "0s"
      directory: "${CASUAL_DOMAIN_HOME}/queue/groups"
    groups:
      - alias: "EXAMPLE"
        queues:
          - name: "ex1"
          - name: "ex2"
  name: test-domain
  servers:
    - instances: 1
      note: exampleserver
      path: ${CASUAL_HOME}/example/bin/casual-example-server