apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: kubectl-run-
spec:
  taskRef:
    name: kubernetes-actions
  serviceAccountName: tekton-pipeline-test
  params:
    - name: script
      value: |
        kubectl get pods 
        echo "-----------"
        kubectl get deploy